//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventEntity
    {
        public System.DateTime eventdt { get; set; }
        public string process { get; set; }
        public string client { get; set; }
        public Nullable<long> transfer { get; set; }
    }
}
