//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageEntity
    {
        public System.DateTime whendt { get; set; }
        public string owner { get; set; }
        public string message1 { get; set; }
        public string stacktrace { get; set; }
    }
}
