//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWWebService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PWEntities : DbContext
    {
        public PWEntities()
            : base("name=PWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerEntity> CustomerEntities { get; set; }
        public virtual DbSet<TransferEntity> TransferEntities { get; set; }
        public virtual DbSet<EventEntity> EventEntities { get; set; }
        public virtual DbSet<MessageEntity> MessageEntities { get; set; }
    }
}
